-- =====================================================
-- ALL 81 TURKISH PROVINCES — CITIES
-- Run AFTER schema.sql + seed.sql
-- seed.sql already inserts 17 cities; this adds the remaining 64
-- =====================================================

-- 1) Update existing cities: ensure has_districts = true for all
UPDATE cities SET has_districts = true WHERE has_districts = false;

-- 2) Insert remaining 64 provinces (existing 17 already in seed.sql)
INSERT INTO cities (name, slug, has_districts, priority) VALUES
  ('Adıyaman',       'adiyaman',       true, 2),
  ('Afyonkarahisar', 'afyonkarahisar', true, 2),
  ('Ağrı',           'agri',           true, 2),
  ('Amasya',         'amasya',         true, 2),
  ('Artvin',         'artvin',         true, 2),
  ('Aydın',          'aydin',          true, 1),
  ('Balıkesir',      'balikesir',      true, 1),
  ('Bilecik',        'bilecik',        true, 2),
  ('Bingöl',         'bingol',         true, 2),
  ('Bitlis',         'bitlis',         true, 2),
  ('Bolu',           'bolu',           true, 2),
  ('Burdur',         'burdur',         true, 2),
  ('Çanakkale',      'canakkale',      true, 2),
  ('Çankırı',        'cankiri',        true, 2),
  ('Çorum',          'corum',          true, 2),
  ('Denizli',        'denizli',        true, 1),
  ('Edirne',         'edirne',         true, 2),
  ('Elazığ',         'elazig',         true, 2),
  ('Erzincan',       'erzincan',       true, 2),
  ('Erzurum',        'erzurum',        true, 1),
  ('Giresun',        'giresun',        true, 2),
  ('Gümüşhane',      'gumushane',      true, 2),
  ('Hakkari',        'hakkari',        true, 2),
  ('Hatay',          'hatay',          true, 1),
  ('Isparta',        'isparta',        true, 2),
  ('Kahramanmaraş',  'kahramanmaras',  true, 1),
  ('Kars',           'kars',           true, 2),
  ('Kastamonu',      'kastamonu',      true, 2),
  ('Kırıkkale',      'kirikkale',      true, 2),
  ('Kırklareli',     'kirklareli',     true, 2),
  ('Kırşehir',       'kirsehir',       true, 2),
  ('Malatya',        'malatya',        true, 1),
  ('Manisa',         'manisa',         true, 1),
  ('Mardin',         'mardin',         true, 2),
  ('Muğla',          'mugla',          true, 1),
  ('Muş',            'mus',            true, 2),
  ('Nevşehir',       'nevsehir',       true, 2),
  ('Niğde',          'nigde',          true, 2),
  ('Ordu',           'ordu',           true, 1),
  ('Rize',           'rize',           true, 2),
  ('Siirt',          'siirt',          true, 2),
  ('Sinop',          'sinop',          true, 2),
  ('Sivas',          'sivas',          true, 2),
  ('Şanlıurfa',      'sanliurfa',      true, 1),
  ('Şırnak',         'sirnak',         true, 2),
  ('Tokat',          'tokat',          true, 2),
  ('Tunceli',        'tunceli',        true, 2),
  ('Uşak',           'usak',           true, 2),
  ('Van',            'van',            true, 1),
  ('Yozgat',         'yozgat',         true, 2),
  ('Zonguldak',      'zonguldak',      true, 2),
  ('Aksaray',        'aksaray',        true, 2),
  ('Bayburt',        'bayburt',        true, 2),
  ('Karaman',        'karaman',        true, 2),
  ('Batman',         'batman',         true, 1),
  ('Düzce',          'duzce',          true, 2),
  ('Osmaniye',       'osmaniye',       true, 2),
  ('Bartın',         'bartin',         true, 2),
  ('Ardahan',        'ardahan',        true, 2),
  ('Iğdır',          'igdir',          true, 2),
  ('Yalova',         'yalova',         true, 2),
  ('Karabük',        'karabuk',        true, 2),
  ('Kilis',          'kilis',          true, 2)
ON CONFLICT (slug) DO NOTHING;
